### PR TITLE
[TASK] Remove duplicate tsconfig

### PR DESCRIPTION
**Pull request by linawolf**
It is already added in Configuration/TSconfig/User

### CODE REVIEW

**Review by brotkrueml — COMMENTED** [review]
Hmm, I would rather remove the Configuration/TsConfig/UserConfiguration.tsconfig.

This file provides a step-by-step guide for configuring a new page type:
Do this, do that, add to top of page tree. So it is not scattered over different places.

**Comment by linawolf** [comment]
I think tsconfig belongs in .tsconfig files...

**Comment by brotkrueml** [comment]
> I think tsconfig belongs in .tsconfig files...

Yes, I may agree, but it depends on the case: Here it is a step-by-step as outlined in the comment before in an example extension. Maybe we can add a comment, that the page type has also to be added in the userTS  in Configuration/TsConfig/.... in this file.

**Comment by linawolf** [comment]
But are these things that belong in the TCA overrides?

**Comment by linawolf** [comment]
I just had a talk with lolli, calling ```ExtensionManagementUtility::addUserTSConfig``` in the TCA overrides does definately not work after the second call as the changes do not get cached.

**Pull request merged**
