### PR TITLE
fix TYPO3 Exception 1303237468

### PR DESCRIPTION
**Pull request by franzholz**
The extension raises an exception when no system extension reactions has been activated.

### CODE REVIEW

**Review by garvinhicking — CHANGES_REQUESTED** [review]
Thanks! I think though the proper fix is to add a dependnecy on sys_reactions. The composer.json already lists this, so it would need to be added to ext_emconf too!

**Comment by franzholz** [comment]
I think it is a bad idea to add dependencies on other extensions. The user should decide what he wants to use.

**Comment by linawolf** [comment]
I agree with @garvinhicking here. the dependencies from the composer.json and the ext_emconf.php should be the same

**Comment by linawolf** [comment]
Thanks a lot for bringing this issue to our notice. It has been resolved with https://github.com/TYPO3-Documentation/t3docs-examples/pull/290

**Comment by franzholz** [comment]
This is a bad solution, because you cannot copy-paste the example and use it for your own extension. Do not forget that the examples from here are used as example code snippets in the TYPO3 documentation.

**Comment by linawolf** [comment]
"Thank you for your feedback, F I understand your concern about making examples as adaptable and flexible as possible for developers who want to use them in their own extensions.

However, I agree with Garvin hat ensuring consistency between composer.json and ext_emconf.php is crucial for maintaining reliable extension behavior. When an extension relies on a specific system extension like EXT:reactions, declaring that dependency in both files is important for preventing unexpected issues, especially for less experienced developers who might not realize the dependency is required.

Regarding your point about copy-pasting examples, I see where you're coming from. While the examples provided in the documentation should indeed be easy to adapt, they also need to reflect best practices to ensure stability and functionality. We want to encourage developers to be mindful of dependencies when integrating example code into their own projects.

If you have ideas on how we can make it clearer that the example is just one way to implement this while still emphasizing the importance of declaring dependencies, we’d love to hear them. Our goal is to provide examples that are both practical and instructive, helping developers avoid common pitfalls.

Thank you for continuing to engage in this discussion. Your input is valuable as we work to create documentation that serves the entire TYPO3 community."

**Pull request closed without merging**
