### PR TITLE
Add required extensions to ext_emconf.php

### PR DESCRIPTION
**Pull request by sypets**
Resolves: #172

### CODE REVIEW

**Review by brotkrueml — COMMENTED** [review]
Hmm, not really sure, if backend, extbase and fluid are needed, as this should be included in "typo3". Maybe also "fluid_styled_content". Haven't found the source of it for "typo3" on the quick run.

**Comment by linawolf** [comment]
I believe we only need to list non-mandatory system extensions? Haven't used TYPO3 without composer in a long time so not sure...

**Comment by brotkrueml** [comment]
> I believe we only need to list non-mandatory system extensions? Haven't used TYPO3 without composer in a long time so not sure...

Yup, which would be linkvalidator and perhaps fluid_styles_content.

**Comment by sypets** [comment]
> Yup, think so, which would be linkvalidator and perhaps fluid_styles_content.

correct.

**Review by linawolf — APPROVED** [review]

**Pull request merged**
