### PR TITLE
fix glob pattern for resource

### PR DESCRIPTION
**Pull request by franzholz**
All files in all folders must be found by the Glob Pattern.
The current pattern will only find the files in the Classes folder.

### CODE REVIEW

**Comment by garvinhicking** [comment]
Thanks for the patch! However: I don't think so, all TYPO3 core sysexts only use this 'Classes/*' pattern, not a single one uses '**'.

I think the reason is that composer receives a list of folders, and it dives any folder it gets. So "**" (any file in any folder) is not needed (and maybe even problematic?)

**Comment by franzholz** [comment]
Uh, I cannot read as fast as you close it.

So you think that the files under the subfolders are not needed? Why aren't they needed also?

**Comment by garvinhicking** [comment]
They are needed - Composer loads all of them. The glob pattern returns a list of directories, not files for this YAML directive :)

**Comment by garvinhicking** [comment]
Correction: Symfony DI seems to do the directory-based resource importing (it's not file based)

**Comment by franzholz** [comment]
The resources glob pattern from Services.yaml has nothing to do with Composer. These files are fetched into your system by Composer. But the PHP processing is done by Symfony. And Symfony uses the glob pattern.  '*' does not search all folders inside of the subfolders. Only '**' does this.
'*' does not match slashes. Therefore the files in folders of the subfolders are not found.

https://stackoverflow.com/questions/55554147/meaning-of-and-other-symbols-in-a-symfony-glob-pattern

https://www.malikbrowne.com/blog/a-beginners-guide-glob-patterns/

The wildcard * stands for "any [string](https://en.wikipedia.org/wiki/String_(computer_science)) of any length including empty, but excluding the path separator characters (/ in unix and \ in windows)".

This means for the example extension that the files inside of /Classes/LinkValidator/LinkType are not matched!

**Comment by garvinhicking** [comment]
It works with the definition in the Core, so IMO no further discussion necessary on this :)

**Comment by franzholz** [comment]
This is no valid argument: "it works for me!".

**Comment by garvinhicking** [comment]
Ok, then the other way: Please explain why it works for every TYPO3-core extension, even though it does not list "../Classes/**". If your statement would be true, it shouldn't work. We cannot change documentation and divert from what the TYPO3 core itself uses.

**Comment by franzholz** [comment]
I have checked the **info** system extension.
Here you have the wrong Services.yaml entry:

     TYPO3\CMS\Info\:
        resource: '../Classes/*'

Why it still works? Just because no Dependendy Injection is used for the classes in the subfolders below the first level folders.

typo3_src-12.4.16/typo3/sysext/info/Classes/Controller/InfoModuleController.php:

            $event = $this->eventDispatcher->dispatch(
            new ModifyInfoModuleContentEvent($accessContent, $request, $this->currentModule, $this->view)
        );

The construction is passing all arguments by itself. It does not use the Dependency Injecion.


typo3_src-12.4.16/typo3/sysext/info/Classes/Controller/Event/ModifyInfoModuleContentEvent.php:

    final class ModifyInfoModuleContentEvent
    {
        private string $headerContent = '';
        private string $footerContent = '';

        public function __construct(
            private readonly bool $access,
            private readonly ServerRequestInterface $request,
            private readonly ModuleInterface $currentModule,
            private readonly ModuleTemplate $moduleTemplate,
        ) {}

@garvinhicking: "We cannot change documentation and divert from what the TYPO3 core itself uses."
  
  Why? TYPO3 should never be programmed based on other search patterns than they are commonly used in all the IT world outside of TYPO3!

**Comment by sbuerk** [comment]
> All files in all folders must be found by the Glob Pattern.
The current pattern will only find the files in the Classes folder.

Please bake your "assumption" / statement with evidence. It's litterally wrong.

**Comment by sbuerk** [comment]
Read up Symfony Finder documentation, it uses single asterix as patterns even for folders:

https://symfony.com/doc/current/components/finder.html

```php
Use * as a wildcard character to search in the directories matching a pattern (each pattern has to resolve to at least one directory path):

 Copy
$finder->in('src/Symfony/*/*/Resources');
```

And as Smyfony DI uses the finder - the same rule applies here. It does not use `glob()` method of PHP/system call.

**Comment by franzholz** [comment]
> ```
> Use *
> ```

I do not get what you mean!
Please explain it!

**Comment by sbuerk** [comment]
> > > All files in all folders must be found by the Glob Pattern.
> > > The current pattern will only find the files in the Classes folder.
> > 
> > 
> > Please bake your "assumption" / statement with evidence. It's litterally wrong.
> 
> This is not an assumption about the Glob Pattern. Check the Glob Pattern syntax and you see that this is the reality.
> 
> But sorry, I did follow the wrong assumption of a Glob Pattern being used for files. I have not seen any documenation about this neither in TYPO3 nor in Symfony.

It was your state ment that all files needs to be found by the glob pattern. Symfony DI(Finder) does not use glob thus this statement from you is wrong.

Using `*` is correct and works. 

> This is not an assumption about the Glob Pattern. Check the Glob Pattern syntax and you see that this is the reality.

Again - you have a wrong assumption here. It does not need to follow glob pattern because the fact is that glob is not used. The Symfony Finder is used within Symfony DI it uses single asterix as pattern placeholder and not the double asterix. Point.

**Comment by franzholz** [comment]
> And as Smyfony DI uses the finder - the same rule applies here. It does not use `glob()` method of PHP/system call.

??? But Symfony uses the Glob pattern. This can be investigated from the PHP Code.

https://github.com/symfony/finder/blob/7.1/Glob.php

**Comment by franzholz** [comment]
Here again that you can see it, that Symfony finder uses the Glob pattern.

https://symfony.com/doc/current/components/finder.html

```
[File Name](https://symfony.com/doc/current/components/finder.html#file-name)
Find files by name with the [name()](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Finder/Finder.php#:~:text=function%20name) method:

 Copy
$finder->files()->name('*.php');
The name() method accepts globs, strings, regexes or an array of globs, strings or regexes:

 Copy
$finder->files()->name('/\.php$/');
```

**Comment by sbuerk** [comment]
> > And as Smyfony DI uses the finder - the same rule applies here. It does not use `glob()` method of PHP/system call.
> 
> ??? But Symfony uses the Glob pattern. This can be investigated from the PHP Code.
> 
> https://github.com/symfony/finder/blob/7.1/Glob.php

Nope. The use a OWN glob implementation and not the native php glob(). Different things.

Again. The syntax is correct. End of discussion.

**Comment by sbuerk** [comment]
> Here again that you can see it, that Symfony finder uses the Glob pattern.
> 
> https://symfony.com/doc/current/components/finder.html
> 
> ```
> [File Name](https://symfony.com/doc/current/components/finder.html#file-name)
> Find files by name with the [name()](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Finder/Finder.php#:~:text=function%20name) method:
> 
>  Copy
> $finder->files()->name('*.php');
> The name() method accepts globs, strings, regexes or an array of globs, strings or regexes:
> 
>  Copy
> $finder->files()->name('/\.php$/');
> ```

Read above - I pasted you the FINDER example for asterix placeholder (pattern) example using the finder compontent right from the symfony documentation.

Maybe you want to fight first with symfony to change their documentation away from how it works to what you mean it should be documented ?

**Comment by franzholz** [comment]
> Maybe you want to fight first with symfony to change their documentation away from how it works to what you mean it should be documented ?

This is nonsense. I have shown the documentation and Symfony PHP code which contradicts your wrong sentence about the Symfony Finder not using Glob patterns. And now you still claim it again and argue that I wanted to fight!

**Comment by mabolek** [comment]
Dear all, please remember to keep a nice and respectful tone and adhere to [TYPO3's Code of Conduct](https://typo3.org/community/values/code-of-conduct#c12422). 🙂

**Comment by franzholz** [comment]
see  #288

**Comment by franzholz** [comment]
Just for the completeness I add this link. There have been more wrong things in the previous discussion about how Symfony works with the glob pattern in Services.yaml.


https://github.com/symfony/symfony/issues/35679 


>  the most common path uses only native glob() function. Symfony\Component\Config\Resource*GlobResource* which is used inside symfony/dependency-injection begins with native glob() function, then extended version from Symfony\Component\Finder*Glob::toRegex*.

**Pull request closed without merging**
